### ISSUE TITLE
GHC 8.10 tracking ticket

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1714]
(Last update: 2020-05-21)

`dhall` is currently blocked on:

* [x] Compatibility with `repline`: #1717
* [x] Compatibility with `template-haskell`: https://github.com/dhall-lang/dhall-haskell/pull/1719
* [x] `serialise`: https://github.com/well-typed/cborg/issues/234

`dhall-lsp-server` is blocked on:

* [X] `haskell-lsp`: https://github.com/alanz/haskell-lsp/issues/239

`dhall-yaml` is blocked on:

* [x] `HsYAML-aeson`: https://github.com/haskell-hvr/HsYAML-aeson/pull/5
* [x] `HsYAML`: https://github.com/haskell-hvr/HsYAML/pull/41

**Comment by sjakobi** [comment]
In `dhall` there are a bunch of warnings like

```
src/Dhall/Set.hs:57:10: warning: [-Wmissing-methods]
    • No explicit implementation for
        ‘Syntax.liftTyped’
    • In the instance declaration for ‘Lift (Set a)’
   |
57 | instance (Data a, Lift a, Ord a) => Lift (Set a) where
```

Apart from that everything seems to _build_ cleanly – I've skipped `dhall-nix` and haven't tested though.

**Comment by sjakobi** [comment]
https://github.com/dhall-lang/dhall-haskell/pull/1775 should address the warnings for the `Lift` instances.

**Comment by sjakobi** [comment]
All the packages except `dhall-nix` can be built with GHC 8.10.1 now. Since we still have #1249 to track `dhall-nix`'s compatibility with GHC 8.8, I'll close this issue for now.
